#Error handling
try:
    print(x)
except:
    print("something went wrong")
else:
    print("Nothing is wrong")
finally:
    print("Try-Except-else is finished")
